-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 11:16:00 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EKM
-- -----------------------------------------------------
-- Outbreak

-- -----------------------------------------------------
-- Schema EKM
--
-- Outbreak`
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EKM` DEFAULT CHARACTER SET utf8 ;
USE `EKM` ;

-- -----------------------------------------------------
-- Table `EKM`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EKM`.`Hospital` (
  `idHospital` VARCHAR(1) NOT NULL,
  `hospitalSite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHospital`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EKM`.`Sex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EKM`.`Sex` (
  `idSex` VARCHAR(1) NOT NULL,
  `patientSex` VARCHAR(10) NULL,
  PRIMARY KEY (`idSex`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EKM`.`County`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EKM`.`County` (
  `idCounty` VARCHAR(1) NOT NULL,
  `countyResidence` VARCHAR(45) NULL,
  PRIMARY KEY (`idCounty`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EKM`.`Symptoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EKM`.`Symptoms` (
  `idSymptoms` VARCHAR(2) NOT NULL,
  `presentedWith` VARCHAR(45) NULL,
  PRIMARY KEY (`idSymptoms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EKM`.`Source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EKM`.`Source` (
  `idSource` VARCHAR(2) NOT NULL,
  `cultureSource` VARCHAR(45) NULL,
  PRIMARY KEY (`idSource`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EKM`.`Died`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EKM`.`Died` (
  `idDied` VARCHAR(1) NOT NULL,
  `patientDied` VARCHAR(3) NULL,
  PRIMARY KEY (`idDied`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EKM`.`Condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EKM`.`Condition` (
  `idCondition` VARCHAR(2) NOT NULL,
  `patientCondition` VARCHAR(45) NULL,
  PRIMARY KEY (`idCondition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EKM`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EKM`.`Events` (
  `idPatient` VARCHAR(15) NOT NULL,
  `patientAge` INT NULL,
  `patientSex` VARCHAR(1) NULL,
  `admissionDate` DATETIME NULL,
  `hospitalSite` VARCHAR(1) NULL,
  `countyRes` VARCHAR(1) NULL,
  `collectionDate` DATETIME NULL,
  `cultureSource` VARCHAR(1) NULL,
  `presentedWith` VARCHAR(1) NULL,
  `patientDied` VARCHAR(1) NULL,
  `patientHad` VARCHAR(2) NULL,
  PRIMARY KEY (`idPatient`),
  INDEX `condition_idx` (`patientHad` ASC),
  INDEX `county_idx` (`countyRes` ASC),
  INDEX `died_idx` (`patientDied` ASC),
  INDEX `hospital_idx` (`hospitalSite` ASC),
  INDEX `sex_idx` (`patientSex` ASC),
  INDEX `source_idx` (`cultureSource` ASC),
  INDEX `symptoms_idx` (`presentedWith` ASC),
  CONSTRAINT `condition`
    FOREIGN KEY (`patientHad`)
    REFERENCES `EKM`.`Condition` (`idCondition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `county`
    FOREIGN KEY (`countyRes`)
    REFERENCES `EKM`.`County` (`idCounty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `died`
    FOREIGN KEY (`patientDied`)
    REFERENCES `EKM`.`Died` (`idDied`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hospital`
    FOREIGN KEY (`hospitalSite`)
    REFERENCES `EKM`.`Hospital` (`idHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sex`
    FOREIGN KEY (`patientSex`)
    REFERENCES `EKM`.`Sex` (`idSex`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `source`
    FOREIGN KEY (`cultureSource`)
    REFERENCES `EKM`.`Source` (`idSource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `symptoms`
    FOREIGN KEY (`presentedWith`)
    REFERENCES `EKM`.`Symptoms` (`idSymptoms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
